---
# python libraries to install via conda
python_libs: 
    - numpy
    - scipy
    - ipython
    - jupyter
    - scikit-learn
    - scikit-image
    - matplotlib
    - ipykernel
    - seaborn
    - h5py
    - pyqt

