---
# General tasks
- block:
  - name: install java
    apt: name=openjdk-7-jre state=present update_cache=yes

  - name: disable net.ipv6.conf.all.disable_ipv6
    sysctl: name=net.ipv6.conf.all.disable_ipv6 value=1 state=present

  - name: disable net.ipv6.conf.default.disable_ipv6
    sysctl: name=net.ipv6.conf.default.disable_ipv6 value=1 state=present

  - name: disable net.ipv6.conf.lo.disable_ipv6
    sysctl: name=net.ipv6.conf.lo.disable_ipv6 value=1 state=present

  - name: distribute host file
    template: src=templates/hosts.j2 dest=/etc/hosts

  - name: install cifs-utils
    apt: name=cifs-utils state=present

  - name: add apt repository for ffmpeg
    apt_repository: repo='ppa:mc3man/trusty-media'

  - name: install ffmpeg
    apt: name=ffmpeg state=present

  tags:
    - general
