---
# Mount external storage using autofs
- block:
  # install autofs
  - name: install autofs
    apt: name=autofs update_cache=yes
  # create mount point (optional)
  - name: Create directory
    file: path=/home/ubuntu/neurophys-storage state=directory
  # copy master config file
  - name: Copy master config
    copy: src=~/helmchen-spark/roles/common/templates/auto.master dest=/etc/auto.master owner=root group=root mode=0644
  # copy cifs config file
  - name: Copy cifs config
    copy: src=~/helmchen-spark/roles/common/templates/auto.cifs dest=/etc/auto.cifs owner=root group=root mode=0644
  # create and edit cifs config file
  # - name: Create cifs config file
  #   file: path=/etc/auto.cifs state=touch
  # - name: Edit cifs config file
  #   lineinfile: dest=/etc/auto.cifs line="/home/ubuntu/neurophys-storage -fstype=cifs,rw,uid=henry,gid=hadoop,credentials=/home/ubuntu/.smbcredentials ://130.60.51.15/Neurophysiology-Storage2"
  # copy .smbcredentials template and modify
  - name: Copy template credentials file
    copy: src=~/helmchen-spark/roles/common/templates/smbcred_templates dest=/home/ubuntu/.smbcredentials owner=ubuntu group=ubuntu mode=0600
  - name: Replace default user name in templates
    replace: dest=/home/ubuntu/.smbcredentials regexp='MYUSERNAME' replace={{smb_password.username}}
  - name: Replace default password in templates
    replace: dest=/home/ubuntu/.smbcredentials regexp='MYPASSWORD' replace={{smb_password.password}}
  # protect credentials file
  # - name: Change file permissions
  #   file: path=/home/ubuntu/.smbcredentials mode=0600
  # start autofs
  - name: Start autofs
    service: name=autofs state=started
  # reload autofs (in case autofs was already running)
  - name: Reload autofs
    service: name=autofs state=reloaded
  tags:
    - autofs
